Testing the latest model

In [1]:
# TensorFlow and tf.keras
import tensorflow as tf

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt
import os
import PIL
import PIL.Image
import pathlib
import cv2

print(tf.__version__)

2.12.0


In [13]:
MODEL_PATH = 'data/model/2023-05-01-15-58-51_sprout_detect'
#IMAGE = 'data/test/seed/2023-04-17__07-34-02__picture.jpg'
IMAGE = 'data/test/sprout/2023-05-01__13-04-03__picture.jpg'


In [14]:
new_model = tf.keras.models.load_model(MODEL_PATH)

# Check its architecture
new_model.summary()


Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 rescaling_2 (Rescaling)     (None, 180, 180, 3)       0         
                                                                 
 conv2d_6 (Conv2D)           (None, 178, 178, 32)      896       
                                                                 
 max_pooling2d_6 (MaxPooling  (None, 89, 89, 32)       0         
 2D)                                                             
                                                                 
 conv2d_7 (Conv2D)           (None, 87, 87, 32)        9248      
                                                                 
 max_pooling2d_7 (MaxPooling  (None, 43, 43, 32)       0         
 2D)                                                             
                                                                 
 conv2d_8 (Conv2D)           (None, 41, 41, 32)       

Load Image and convert to share (None, 180, 180, 3)

In [15]:
image_raw = cv2.imread(IMAGE, 3)

resized_image = cv2.resize(image_raw, (180, 180))
image=np.expand_dims(resized_image, axis=0)

Classify Image

In [20]:
result = new_model.predict(image)
print(result)

1/1 [==============================] - 0s 12ms/step
[[-0.3596344  5.7057385]]


Test Seed Pictures

In [27]:
files = os.listdir('data/test/seed')

for file in files:
    image_raw = cv2.imread('data/test/seed/' + file, 3)
    resized_image = cv2.resize(image_raw, (180, 180))
    image=np.expand_dims(resized_image, axis=0)
    result = new_model.predict(image)
    print(result)


1/1 [==============================] - 0s 17ms/step
[[5.4203973  0.40972325]]
1/1 [==============================] - 0s 9ms/step
[[5.253712  0.5522889]]
1/1 [==============================] - 0s 9ms/step
[[5.539456   0.35531753]]
1/1 [==============================] - 0s 10ms/step
[[5.488952   0.35734823]]
1/1 [==============================] - 0s 10ms/step
[[5.223324   0.55760854]]
1/1 [==============================] - 0s 9ms/step
[[5.5237713 0.3584832]]
1/1 [==============================] - 0s 10ms/step
[[5.3319287  0.45500952]]
1/1 [==============================] - 0s 11ms/step
[[4.7557597 0.9382429]]
1/1 [==============================] - 0s 10ms/step
[[5.405621  0.3968051]]
1/1 [==============================] - 0s 10ms/step
[[5.5212674  0.35973096]]
1/1 [==============================] - 0s 11ms/step
[[5.3370423  0.50755304]]
1/1 [==============================] - 0s 10ms/step
[[5.2473717  0.42726237]]
1/1 [==============================] - 0s 9ms/step
[[5.253966  0.5514452]]


Test Sprout Pictures

In [26]:
files = os.listdir('data/test/sprout')

for file in files:
    image_raw = cv2.imread('data/test/sprout/' + file, 3)
    resized_image = cv2.resize(image_raw, (180, 180))
    image=np.expand_dims(resized_image, axis=0)
    result = new_model.predict(image)
    print(result)


1/1 [==============================] - 0s 10ms/step
[[-5.4348583  9.66458  ]]
1/1 [==============================] - 0s 9ms/step
[[-4.105729  8.445781]]
1/1 [==============================] - 0s 10ms/step
[[-4.9155474  8.947023 ]]
1/1 [==============================] - 0s 9ms/step
[[-5.0518503  8.95053  ]]
1/1 [==============================] - 0s 9ms/step
[[-5.3657966  9.464782 ]]
1/1 [==============================] - 0s 10ms/step
[[-5.2109046  9.057031 ]]
1/1 [==============================] - 0s 10ms/step
[[-0.5033426  5.7520633]]
1/1 [==============================] - 0s 10ms/step
[[-4.274238  8.481693]]
1/1 [==============================] - 0s 9ms/step
[[-5.174563  9.495382]]
1/1 [==============================] - 0s 9ms/step
[[-0.6061201  5.8253317]]
1/1 [==============================] - 0s 9ms/step
[[-0.45343965  5.720588  ]]
1/1 [==============================] - 0s 9ms/step
[[-0.67929125  5.86157   ]]
1/1 [==============================] - 0s 9ms/step
[[-4.5717406  8.78625 